source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3'
gem 'rabl'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'handlebars_assets'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'backbone-on-rails'
gem 'eco'
gem 'devise'
gem 'paperclip'
gem 'rails_admin', :git => 'https://github.com/sferik/rails_admin.git'

group :development do
  gem 'guard'
  gem 'guard-test'
  gem 'growl'
  gem 'ruby_gntp'
end

group :test do
  gem 'database_cleaner'
  gem 'capybara'
  gem 'poltergeist'
end
gem 'faker'
