source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'sqlite3'
gem 'rabl'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'handlebars_assets'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'paperclip'
gem 'backbone-on-rails'
gem 'eco'
gem 'faker'
