source 'https://rubygems.org'

gem 'rails', '3.2.6'
gem 'rails-api'
gem 'rabl'
gem 'sqlite3'
gem 'paperclip'
gem 'backbone-on-rails'
gem 'eco'
gem 'faker'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
